### ISSUE TITLE
rename `Control.Placeholder` to `Develop.Placeholder`

### ISSUE THREAD

**Issue by MangoIV** [ekmett/placeholder#5]
While agree, that `Debug` is not the correct namespace for these, I also think `Control` is not. Perhaps `Develop` is a good idea (as proposed in the discussion in the `CLC` proposal)

**Comment by ekmett** [comment]
My major concern with `Develop` is that at least `unimplemented` seems intended to stick around long term. So if the purpose of a `Develop` namespace is to place transitory things that will be removed when you are done with your task, then this also seems off.

**Comment by ekmett** [comment]
The justification for `Control` to me is based on the traditional split between `Control` and `Data`, this isn't actually a *data* structure you manipulate, but it does affect the *control* flow of your program (by stopping). A lesser justification that I don't really buy is that by making them actual named exceptions they allow what is in theory resumable usable control flow.

**Comment by MangoIV** [comment]
Makes sense, yeah I didn’t really think about unimplemented vs todo, if there’s only todo, it makes much more sense.
